---
name: Deploy

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    container: node:20-alpine
    steps:
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pnpm i
      - name: Build the site
        run: pnpm run build
        env:
          API_URL: https://api.pantry.nickelghost.com
          FIREBASE_API_KEY: '${{ secrets.FIREBASE_API_KEY }}'
          FIREBASE_PROJECT_ID: personal-419019
          FIREBASE_AUTH_DOMAIN: pantry.nickelghost.com
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}'
          projectId: personal-419019
          channelId: live
